name: On the push of a tagged commit to master, create a release and publish to PyPI

on:
  pull_request:
    branches:
      - 'master'

jobs:
  build-n-publish:
    name: Build and publish Python distributions
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@master

        - name: Set up Python 3.6
          uses: actions/setup-python@v1
          with:
            python-version: 3.6

        - name: Install and upgrade pip, setuptools and wheel
          run: >-
            pip
            install
            --upgrade
            pip
            setuptools
            wheel

        - name: Build a binary wheel and a source tarball
          run: >-
            python
            setup.py
            sdist
            bdist_wheel
            --universal

        - name : Generate a Release Message
          run: export RELEASE_MSG=RELEASE_MESSAGE=$( git log master..develop --format=%s | grep -v 'Merge' | grep -v 'readme' )
          shell: bash

        - name: Create Release on GitHub
          uses: actions/create-release@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            body: ${{ RELEASE_MSG=RELEASE_MESSAGE }}
            draft: false
            prerelease: false

        - name: Publish distribution to PyPI
          if: startsWith(github.event.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.pypi_password }}